# Generated by Django 2.2.6 on 2019-11-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191112_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sub_id',
            new_name='substitute',
        ),
    ]
