# Generated by Django 2.2.6 on 2019-11-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191026_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutri_score',
            field=models.ImageField(db_index=True, upload_to='images/'),
        ),
    ]
